// flow-typed signature: 1d37c08ef921ae4db8e05df2fcc38bf9
// flow-typed version: <<STUB>>/react-slick_v0.14.6/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-slick'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-slick' {
  declare var exports: any;
}
